import type { Dataset } from "@/lib/types";
/**
 * Real BLS-derived labour rates. Generated by scripts/ingest-bls-oews.ts and
 * committed, so this is a static import on purpose: if the file goes missing
 * the build fails loudly. It used to be an optional `require` in a try/catch,
 * which meant a resolution failure silently reverted the whole site to sample
 * wages while still rendering as though nothing had changed. On a product whose
 * entire claim is that it shows you where its numbers came from, that is the
 * worst possible failure mode.
 */
import { blsLaborRecords } from "./bls-labor";
import { observedMaterialRecords } from "./materials";
import { countries, metros, states } from "./geo";
import { cities } from "./cities";
import { zipCodes } from "./zips";
import { materials, projectTypes, services } from "./catalog";
import {
  priceIndexPoints, priceIndexSeries, pricingFactors, pricingRecords, pricingSources,
} from "./pricing";

/**
 * A metro-scoped BLS rate is useless while a sample city-scoped rate still
 * exists, because a finer geographic scope always wins the lookup. So the
 * sample city labour rows are dropped the moment real ones arrive.
 */
const labourRecords = blsLaborRecords.length
  ? [
    ...pricingRecords.filter(
      (r) => !(r.metricKey === "labor.rate_per_hour"
        && r.geoScopeType === "city"
        && r.dataStatus === "sample")),
    ...blsLaborRecords,
  ]
  : pricingRecords;

/**
 * Observed material prices replace the sample row for the same material, they
 * do not sit alongside it.
 *
 * Both are country-scoped, so the geographic chain cannot separate them and
 * whichever the index happened to return first would win. Two rows for one
 * material is not a richer dataset, it is a coin toss over which price the
 * site publishes.
 *
 * Only the materials actually collected are replaced. The other twelve keep
 * their sample rows and go on saying so.
 */
const supersededByObservation = new Set(
  observedMaterialRecords.map((r) => `${r.metricKey}::${r.materialId ?? ""}`));

const allRecords = observedMaterialRecords.length
  ? [
    ...labourRecords.filter(
      (r) => !supersededByObservation.has(`${r.metricKey}::${r.materialId ?? ""}`)),
    ...observedMaterialRecords,
  ]
  : labourRecords;

export const seedDataset: Dataset = {
  countries, states, metros, cities, zipCodes,
  services, projectTypes, materials,
  pricingSources, pricingRecords: allRecords, pricingFactors,
  priceIndexSeries, priceIndexPoints,
};

/** True when real wage data is in play rather than sample rates. */
export const hasRealLabourData = blsLaborRecords.length > 0;

/** Material slugs whose price is observed rather than modelled from nothing. */
export const observedMaterialSlugs = new Set(
  observedMaterialRecords.map((r) => (r.materialId ?? "").replace(/^mat-/, "")));

export { SEED_COLLECTED_DATE, SEED_EFFECTIVE_DATE } from "./pricing";
