import type { Dataset } from "@/lib/types";
/**
 * Real BLS-derived labour rates. Generated by scripts/ingest-bls-oews.ts and
 * committed, so this is a static import on purpose: if the file goes missing
 * the build fails loudly. It used to be an optional `require` in a try/catch,
 * which meant a resolution failure silently reverted the whole site to sample
 * wages while still rendering as though nothing had changed. On a product whose
 * entire claim is that it shows you where its numbers came from, that is the
 * worst possible failure mode.
 */
import { blsLaborRecords } from "./bls-labor";
import { countries, metros, states } from "./geo";
import { cities } from "./cities";
import { zipCodes } from "./zips";
import { materials, projectTypes, services } from "./catalog";
import {
  priceIndexPoints, priceIndexSeries, pricingFactors, pricingRecords, pricingSources,
} from "./pricing";

/**
 * A metro-scoped BLS rate is useless while a sample city-scoped rate still
 * exists, because a finer geographic scope always wins the lookup. So the
 * sample city labour rows are dropped the moment real ones arrive.
 */
const labourRecords = blsLaborRecords.length
  ? [
    ...pricingRecords.filter(
      (r) => !(r.metricKey === "labor.rate_per_hour"
        && r.geoScopeType === "city"
        && r.dataStatus === "sample")),
    ...blsLaborRecords,
  ]
  : pricingRecords;

export const seedDataset: Dataset = {
  countries, states, metros, cities, zipCodes,
  services, projectTypes, materials,
  pricingSources, pricingRecords: labourRecords, pricingFactors,
  priceIndexSeries, priceIndexPoints,
};

/** True when real wage data is in play rather than sample rates. */
export const hasRealLabourData = blsLaborRecords.length > 0;

export { SEED_COLLECTED_DATE, SEED_EFFECTIVE_DATE } from "./pricing";
